<td id="content">
<p class="positionlink">whiskyfreunde</p>
	<!-- header -->
	<h1 class="mainheader">Die Whiskyfreunde stellen sich vor</h1>


<p>
<table cellpadding="20" border="0">
<tr>
  <td align="center" valign="top"><img  src="pics/kristof.gif" width="100" alt="" border="0"></td>
  <td valign="top"><p><b>Krzysztof Wrobel</b></p>
  <ul>
   <li>*12.03.1977
   <li>Berufssoldat
   <li>Er bringt euch den Frieden
   <li>Er mag die Burger blutig und die Whiskies rauchig
  </ul></td>
</tr>
<tr>
  <td align="center" valign="top"><img  src="pics/matthias.gif" width="100" alt="" border="0"></td>
  <td valign="top"><p><b>Matthias Faust</b></p>
  <ul>
  <li>*08.04.1977
  <li>Diplom Informatiker
  <li>der einzige unter 1,90 m
  <li>Der Weiche unter den Harten
  </ul></td>
</tr>
<tr>
  <td align="center" valign="top"><img  src="pics/volker.gif" width="100" alt="" border="0"></td>
  <td valign="top"><p><b>Volker Steinhoff</b></p>
  <ul>
  <li>*07.01.1971
  <li>Dipl. Bauingenieur
  <li>Der grösste Schlagzeuger der Welt
  <li><b>"LAST CALL" </b>for alcohol
  </ul></td>
</tr>
<tr>
  <td align="center" valign="top"><img  src="pics/thomas.gif" width="100" alt="" border="0"></td>
  <td valign="top"><p><b>Thomas Steinhoff</b></p>
  <ul>
  <li>*04.08.1965
  <li>Arbeitspädagoge und Tontechniker
  <li>Der Macher
  <li>Portwood über alles oder:"Es darf auch mal ein wenig Islay-iger sein."
  <li>Irish Wolfhound Besitzer 
  <li>The Bassman
  </ul></td>
</tr>
<tr>
  <td align="center" valign="top"><img  src="pics/ralph.gif" width="100" alt="" border="0"></td>
  <td valign="top"><p><b>Ralf Dickmann</b></p>
  <ul><li><b>"Der Senat"</b>
  <li>alias Lauterleiser
  <li>*07.06.1965
  <li>Dipl. Sozialarbeiter und Tontechniker
  <li>Islay-Liebhaber
  <li>Murmel-König
  <li>Boxer-Freund
  </ul></td>
</tr> 
</table>

</p>


</td>
<td id="subcontent">
<div>
</div>
</td>
