<td id="content">
<p class="positionlink">gasttrinker</p>
	<!-- header -->
	<h1 class="mainheader">Gasttrinker</h1>

	<p>Unsere Gasttrinker</p>

<h2>Es waren anwesend und haben sich Ehre und Ruhm verdient:</h2> 


<p>Wolfgang Hillmann</p>
<p>Michael Farsch</p>
<p>René Kallinowski</p>
<p>André Postier</p>
<p>Daniel Geimer</p>

<h2>Es verdient den Pranger  und ist damit raus bis ans Ende aller Tage:</h2>
<p>Michael Postier - vergessen</p>
<p>Frank Bücker - vergessen und eigene Party im Haus</p>
<p>André Schemmerling - zu weit zu fahren (Bonn)</p>
<p>Michael Wrobel - Silberhochzeit der Eltern seiner Ex-Freundin</p>


</td>
<td id="subcontent">
<div>
</div>
</td>
