<td id="content">

<!-- header -->
<h1>Impressum</h1>
<p>Whiskyfreunde Oelde</p>
<script type="text/javascript">
					<!--
					var s1 = '<p>email <a href="mailto:';
					var s2 = 'mail';
					var s3 = '@whisky';
					var s4 = 'freunde.net';
					var s5 = '">';
					var s6 = '</a></p>';
					document.write(s1+s2+s3+s4+s5+s2+s3+s4+s6);
					//-->
                    		</script>
				<noscript>
					contact
				</noscript>
<h2>Verantwortlich für den Inhalt</h2>
<p>Matthias Faust</p>
<h2>Design und Implementierung</h2>
<p>Matthias Faust</p>
<h2>Bilder</h2>
<p>Some pictures used on this website are provided by www.photocase.com</p>
</td>
<td id="subcontent">
<div>
<!-- <h1>FLink Workflow</h1>
<p></p>
-->
</div>
</td>
