<a href="index.php?page=overview">home</a>
<a href="index.php?page=news">news</a>
<a href="index.php?page=friends">whiskyfreunde</a>
<a href="index.php?page=guests">gasttrinker</a>
<a href="index.php?page=links">links</a>
<a href="contact.php">kontakt</a>
								<br>
<a href="http://www.disclaimer.de/disclaimer.htm?farbe=FFFFFF/000000/000000/000000" target="_blank">disclaimer</a>
<a href="index.php?page=imprint">impressum</a>									